# Doks params.toml
[doks]
colorMode = "auto"
colorModeToggler = true
navbarSticky = true
containerBreakpoint = "lg"
navBarButton = false
navBarButtonUrl = "/docs/prologue/introduction/"
navBarButtonText = "Get started"
flexSearch = true
flexSearchConfig = "js/flexsearch.pt.js"
searchExclKinds = ["taxonomy", "term"]
showSearch = []
indexSummary = false
showDate = false
showSummary = true
searchLimit = 99
alert = false
alertDismissable = true
bootstrapJavascript = false
sectionNav = ["docs"]
toTopButton = false
breadcrumbTrail = false
headlineHash = true
scrollSpy = true
multilingualMode = false
showMissingLanguages = true
docsVersioning = false
docsVersion = "1.0"
headerBar = false
backgroundDots = true
sectionFooter = false
relatedPosts = false
imageList = true
imageSingle = true
editPage = false
lastMod = false
repoHost = "GitHub"
docsRepo = "https://github.com/h-enk/doks"
docsRepoBranch = "main"
docsRepoSubPath = ""
krokiURL = "https://kroki.io"
